### ISSUE TITLE
created_stamp and last_updated_stamp NOT work

### ISSUE THREAD

**Issue by dungkhmt** [dungkhmt/baseweb#4]

**Comment by tuandat95cbn** [comment]
do you add last_updated_stamp trigger for the table?
Ex: `CREATE TRIGGER user_login_security_group_last_updated_stamp
  BEFORE UPDATE
  ON user_login_security_group
  FOR EACH ROW EXECUTE PROCEDURE set_last_updated_stamp();` 
and set default for created_stamp 
Ex: `created_stamp      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,`
